name: Test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        cache: maven
    - name: Build parent
      run: mvn --batch-mode --update-snapshots clean install -Dmaven.test.skip
    - name: Unit Tests
      run: mvn --batch-mode test
    - name: Integration Tests
      run: mvn --batch-mode failsafe:integration-test failsafe:verify -Dskip.surefire.tests