name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: true

jobs:
  test:
    uses: ./.github/workflows/build.yml

  release:
    needs: [test]
    # if: github.ref == 'refs/heads/master'
    uses: malkusch/github/.github/workflows/maven-central-release.yml@modules
    with:
      PREPARE_ARGUMENTS: "-P oss-parent-test"
      dry-run: ${{ inputs.dry-run }}
      JDK_VERSION: ${{ needs.test.outputs.JDK_VERSION }}
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      MAVEN_GPG_PRIVATE: ${{ secrets.MAVEN_GPG_PRIVATE }}
